pipelines:
  branches:
    main:
      - step:
          name: Deploy on Same Server
          runs-on:
            - self.hosted
            - linux.shell
          working_directory: /home/ubuntu/gms-be
          script:
            - echo "🚀 Starting deployment..."

            - echo "🔑 Setting permissions..."
            - sudo -u ubuntu chown -R ubuntu:ubuntu /home/ubuntu/gms-be
            - cd /home/ubuntu/gms-be
            - cp .env ../
            - echo "🛑 Stopping old PM2 process..."
            - pm2 stop gms-be || true
            - pm2 delete gms-be || true

            - echo "🔄 Updating code..."
            - git clean -fdx
            - git fetch --all
            - git reset --hard origin/main

            - echo "🧹 Cleaning dependencies & Prisma..."
            - npm cache clean --force
            - cp /home/ubuntu/.env /home/ubuntu/gms-be

            - echo "📦 Installing dependencies..."
            - npm install
            - npx prisma generate


            - echo "🏗️ Building project..."
            - npm run build

            - echo "🚀 Starting PM2..."
            - pm2 start /home/ubuntu/gms-be/dist/src/main.js --name gms-be

            - echo "✅ Deployment completed!"
