image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Prod Server
          script:
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: $sshuser
                SERVER: $prodip
                COMMAND: |
                  bash -lc "
                    sudo chown -R ubuntu:ubuntu /home/ubuntu/gms-be
                    cd /home/ubuntu/gms-be
                    sudo pm2 stop gms-be
                    echo '🔄 Resetting to latest main...'
                    git fetch origin main
                    git reset --hard origin/main
                    git pull origin main

                    echo '🧹 Cleaning old Prisma & node_modules...'
                    rm -rf node_modules/.prisma
                    rm -rf node_modules/@prisma
                    rm -rf node_modules package-lock.json
                    npm cache clean --force

                    echo '📦 Installing dependencies...'
                    npm install

                    echo '⚙️ Generating Prisma client...'
                    chmod +x node_modules/.bin/prisma || true
                    npx prisma generate

                    echo '🏗️ Building project...'
                    npm run build

                    echo '🚀 Restarting PM2...'
                    sudo pm2 restart gms-be
                  "
