version : "3.8"
services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - halcon
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - halcon
networks:
  halcon:


  
